right_format = """
$time"""

[time]
disabled = false
time_format = "%r"
utc_time_offset = '5.5'
# style = "bold yellow"
# format = '[$time ]($style)'
style = "bg:#1d2230"
format = '[[$time ](fg:#d79921 bg:#1d2230)]($style)'

[cmd_duration]
min_time = 0
show_milliseconds = true
